ARG ELK_VERSION

# https://www.docker.elastic.co/
FROM 192.168.1.125:8181/elasticsearch/elasticsearch:${ELK_VERSION}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
