ARG ELK_VERSION

# https://www.docker.elastic.co/
FROM 192.168.1.125:8181/logstash/logstash:${ELK_VERSION}

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
